### ISSUE TITLE
Data science jobs

### ISSUE THREAD

**Issue by ZionCodes** [Nithur-M/work-from-anywhere#1]
Please include data science jobs

**Comment by Nithur-M** [comment]
Sure, I'll work on it tomorrow. Thanks for letting me know.

**Comment by Nithur-M** [comment]
Hi, added support for data science jobs. Currently, there is no data science job that recruits worldwide from those job boards we source jobs. But it will be updated if there is any data science jobs. Please keep a watch on it. Thank you.
